on: [release]

jobs:
  release:
    - uses: MCJack123/ghaction-generate-release-hashes@v4
      with:
        hash-type: sha256
        file-name: hashes.txt
    - uses: actions/upload-artifact@v2
      with:
        name: Asset Hashes
        path: hashes.txt
